### ISSUE TITLE
Centos 6.3 编译不了

### ISSUE THREAD

**Issue by lonestonewy** [baogaitou/spx2wav#2]
gcc -g -c -o SpeexDecode.o SpeexDecode.c -I./speex  -lspeex
gcc -g -c -o fifo.o fifo.c -I./speex  -lspeex
gcc -g -o spx2wav SpeexDecode.o TRSpeex.o fifo.o -I./speex  -lspeex
TRSpeex.o: could not read symbols: File in wrong format
collect2: ld returned 1 exit status
make: *** [spx2wav] Error 1

啥情况？

**Comment by baogaitou** [comment]
先安装 speex-devel:  yum install speex-devel 
然后使用我的 makefile 来编译, 我也是在 CentOS 下使用.

**Comment by mejinke** [comment]
我也遇到这个问题，不知道怎么解决。。 speex-devel安装了。makefile怎么用？
没搞过C.

**Comment by baogaitou** [comment]
用 gcc 编译.

**Comment by Aaron-wlh** [comment]
-bash-4.1$ make
gcc -g -c -o SpeexDecode.o SpeexDecode.c -I./speex  -lspeex
gcc -g -c -o TRSpeex.o TRSpeex.c -I./speex  -lspeex
gcc -g -c -o fifo.o fifo.c -I./speex  -lspeex
gcc -g -o spx2wav SpeexDecode.o TRSpeex.o fifo.o -I./speex  -lspeex
-bash-4.1$ cp spx2dev /usr/local/bin
cp: cannot stat `spx2dev': No such file or directory

我make之后显示没有spx2dev这个目录啊
只有以下目录
```
fifo.c  fifo.o    README.md  SpeexDecode.c  spx2wav    TRSpeex.h
fifo.h  Makefile  speex      SpeexDecode.o  TRSpeex.c  TRSpeex.o
```

**Comment by baogaitou** [comment]
> -bash-4.1$ make
> gcc -g -c -o SpeexDecode.o SpeexDecode.c -I./speex -lspeex
> gcc -g -c -o TRSpeex.o TRSpeex.c -I./speex -lspeex
> gcc -g -c -o fifo.o fifo.c -I./speex -lspeex
> gcc -g -o spx2wav SpeexDecode.o TRSpeex.o fifo.o -I./speex -lspeex
> -bash-4.1$ cp spx2dev /usr/local/bin
> cp: cannot stat `spx2dev': No such file or directory
> 
> 我make之后显示没有spx2dev这个目录啊
> 只有以下目录
> 
> ```
> fifo.c  fifo.o    README.md  SpeexDecode.c  spx2wav    TRSpeex.h
> fifo.h  Makefile  speex      SpeexDecode.o  TRSpeex.c  TRSpeex.o
> ```

抱歉, makefile 已经修正. spx2dev 应该修改为 spx2wav, spx2wav 就是编译出来的可执行文件.
