### ISSUE TITLE
微信高清语音文件speex转wav, windows下可执行的EXE spx2wav.exe 供ASP.NET使用

### ISSUE THREAD

**Issue by lpfy** [baogaitou/spx2wav#3]
感谢作者把一切都打包好了，由于项目用的win2012R2，所以不得不自己用cygwin编译了一个windows下可执行的EXE spx2wav.exe。有用WIN服务器和ASP.NET的同学，可以下载链接: https://pan.baidu.com/s/1kUqv8eK1ZpvbBHxo17kR4w 提取码: r2ta

**Comment by baogaitou** [comment]
手动点赞:)
